travis:
  secure:
    BINSTAR_TOKEN: dHTSzoEpPFO3d1fFVRM8H5l90dL2NF1MztE12wyrO6dgJT0HOntVev9V45aXI1Sc+FcKNs3fmHpuoQG2ZF5HUpM9B22Nk/bLl3HL29xbTsTQB/DntSXgjo0duEWj2oAnDEq/rjbbd1Wr+/0o/2fLy8JwedSQFa4iDO+z1yQ9hWWmmO1eWE4xdH6q1oo9dapmHT0wlgxfE98G6iE3yWcf7l/3xwpEI1PKE5CV+7AHRdtXCG7nGL5KQJ4oUfPZSx5R0Gj2wItkhJ9YP74/ZXsNe2SS+B6hkMC7WX1v7Kbph8ptv2JogX5bew6cuYlU75ePrhFQ6obbbZROtU7sjQGlrolgXXqNCbZLfDszl9tyaaL8i1z8PyPsKRLt2Uc9IRoR7pY2UM2DgzgDfQRcCvOx7veaOdl1OYa5YZh9s47YK9R8HAh0Hg2ux2uSl7bVHXZVOvxJPy7UvSg68odPkGnXqKXc96IagJzJ3/pCQahPAzvtF9tmQ3La4guGqhVfCY+KTljQ/W6qMmJEcxdOKQaElQqQHaiHTFr+brxsWLrlFV7ECdNDDkVcDJm52jgTzJCDdFik+CtL+p4rQ/zQHgZGg7dgsWuAb5YHzg6GSZocfFaoa/4nwSWcK918RMAhHuV1WZ1w+Vc/17ID9ep33i6o7NDKhsrhrkr9AceaJAfepTc=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
