appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
travis:
  secure: {BINSTAR_TOKEN: QXGgsTvA/nJuCROHk80jM4uvvgOcVXHyz3k2ErnCUQe/kbVMpdeunea1qAcXlpCA0QeWwHH+FLlVtBA4Hat56zgyFNzYWh1jwalWBj11N0hrw+WyT0Jji9jCzYZ7ywYlJRNUGkLj27MkebO2E9vEuacX5kN1KK53MCFbZGBRYeohAODBJrFOGmINJzWzGerPqdeVV/TIbg4ZSA+pztzWa3D2wXLuZVTL3t5q3EIGaTuQD1fwqcC4P8+PlbYdYYD0Y4dL4w73lhGKHsWEr5KeGcmqUQ03TiVZz1YII728j86RNTA/Lb5QkEG0iHjEDZxPJvApbIpHnyQ1fj9difFFfVddsKHyXg7s08TgzuCWrqXfwNRWhPGxeCGRB7cW/ERIVLS6BQcBaC1rb4W5BWr5/Oti6cPw5shqb7N8eDz5CcsFFOowOa8Fm3M2oROjpFocjryM+VWeTfUZkRU34TDWVM4JDNso2MEYUViecj1Ux5ovUVzsn/v8RsVRkL2PfcvwBm6Z+IDLxKax4XHyOmSp+zDtljXO/m3JZFE3Bw1tGLe/hcmh3owYGkGzNLbwFjOF/XpUN/3a1Fw4XjgqfbOQ2bd8fPZvzFjgxZLTquzLZDBJW43srbINaLHxh2upf0YCpeqDPj3UiLn2BSXUR2WU5hlaf9mj39i7gHFc9BfpucY=}
provider:
  win: azure
conda_forge_output_validation: true
