travis:
  secure:
    BINSTAR_TOKEN: sWrfRGZTyzf0lMmL1v9WbOwV75PNeyacSjz0QqSVszoOROFD6llqLKrpet1ldhpZQW5OqiWiqmW3Da6zveeioiK30JqU3lbcfVD1Yy2QJu1VpZxTza1ORoOhStGzKj7mocDGGSmlfdm7t24Iedl/E0WuQUWX2W99sXo/wpAYEBm5caYOiJuxFUF9we7O0h80hxVezUhg4eSwF5J0IINfvT/sfbckQOMz9Km8BZTCDH1R2XDsX94qC3N7GPlUmcBqh2MwhkOH0C+igoIHbzlMlm/Lmo4IH6VHQjZn9O+B5vRqgieH/C5umUdICiXOG5CrC9mhFQKT/IjZS3FvEmLoEXSSFcYLO0UopBstza3TQePwnfrOXvdaWRakm6uENcWiems7ZlXpfIChNJJggZtQHnJxkkEG9taa27/+oMckgMLgax09Sa7n41sjLCOiw8juSUzRQV+eK288ariqisZP2njUZ8PF22h1/EAfVjdGvUATfVLDQMAEAcVRLodwfW/FLh7r/JJPkgQvCkLXN5otkzMjkje9u1JUmsxsFm5D4xIwKvo6D7h8gqxyZ2FnGPyV4VRxdH6pPv7aK3eku59+GLj9Sow6l+lbPl1JyIJihXIv0Z7pPTFg8odayyRxaPhe/mUEjPn2hRSqg/8bjkBNvd2ziWZZEMXfwRUapV/GdB4=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
